spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tenant_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: test
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 30001
# Mybatis 配置
mybatis-plus:
  #mapper-locations: classpath*:mapping/*Mapper.xml
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dev.happy.tenant.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
logging:
  level:
    com:
      dev:
        happy:
          tenant:
            mapper: debug
app:
  home-url: http://localhost:30001/home